config/routes.rb
Rails.application.routes.draw do
  resources :elastic_searches
  resources :redis
  resources :postgresqls
  resources :secrets
  resources :application_environments
  resources :environments
  resources :applications
  devise_for :users
  root to: "home#index"
end

app/models/application.rb
class Application < ApplicationRecord
  has_many :application_environments, dependent: :destroy
  has_many :environments, through: :application_environments
  has_many :secrets, through: :application_environments
  has_many :postgresqls, through: :application_environments
  has_many :redis, through: :application_environments
  has_many :elastic_searches, through: :application_environments

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from DeviseLdapAuthenticatable::LdapException do |exception|
    render :text => exception, :status => 500
  end
  protect_from_forgery with: :exception
end

app/controllers/applications_controller.rb
class ApplicationsController < LoggedInController # < ApplicationController
  before_action :load_application, only: [:show, :edit, :update, :destroy]
  respond_to :html

  def index
    @applications = Application.all
  end

  def show
    respond_with @application
  end

  def new
    @application = Application.new
  end

  def edit
    respond_with @application
  end

  def create
    @application = Application.new(application_params)
    flash[:notice] = "Application was successfully created." if @application.save
    respond_with @application
  end

  def update
    if @application.update(application_params)
      flash[:notice] = "Application was successfully updated."
    end
    respond_with @application
  end

  def destroy
    @application.destroy
    flash[:notice] = "Application was successfully destroyed."
    respond_with @application
  end

  private

  def load_application
    @application = Application.find(params[:id])
  end

  def application_params
    params.require(:application).permit(:name, :uses_sidekiq, :uses_postgres, :uses_redis, :uses_ldap)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_form.html.haml
= simple_form_for @application, html: { class: "form-horizontal" },
                                               wrapper: :horizontal_form do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :uses_sidekiq
    = f.input :uses_postgres
    = f.input :uses_redis
    = f.input :uses_ldap

  .form-actions
    = f.button :submit, class: "btn btn-primary"

app/views/applications/edit.html.haml
- title "Editing application"

= render "form"

%br
= link_to "Show", @application, class: 'btn btn-sm btn-success'
\|
= link_to "Back", applications_path

app/views/applications/index.html.haml
- title "Applications"

%table.table.table-condensed
  %thead
    %tr
      %th Name
      %th Sidekiq
      %th PostgreSQL
      %th Redis
      %th ElasticSearch
      %th Secrets
      %th

  %tbody
    - @applications.each do |application|
      %tr
        %td= application.name
        %td= application.redis.empty? ? "✘" : "✓"
        %td= application.postgresqls.empty? ? "✘" : "✓"
        %td= application.redis.empty? ? "✘" : "✓"
        %td= application.elastic_searches.empty? ? "✘" : "✓"
        %td= application.secrets.empty? ? "✘" : "✓"
        %td
          = link_to "Show", application, class: "btn btn-xs btn-success"
          = link_to "Edit", edit_application_path(application), class: "btn btn-xs btn-info"
          = link_to "Destroy", application, :method => :delete,
                               :data => { :confirm => "Are you sure?" },
                               class: "btn btn-xs btn-danger"

%br

= link_to "New Application", new_application_path, class: "btn btn-primary"

app/views/applications/new.html.haml
- title "New application"

= render "form"

%br
= link_to "Back", applications_path

app/views/applications/show.html.haml
- title "application #{@application.id}"
%p
  %b Name:
  = @application.name
%p
  %b Uses sidekiq:
  = @application.uses_sidekiq
%p
  %b Uses postgres:
  = @application.uses_postgres
%p
  %b Uses redis:
  = @application.uses_redis
%p
  %b Uses ldap:
  = @application.uses_ldap

%br
= link_to "Edit", edit_application_path(@application), class: 'btn btn-sm btn-primary'
\|
= link_to "Back", applications_path