config/routes.rb
Rails.application.routes.draw do
  resources :elastic_searches
  resources :redis
  resources :postgresqls
  resources :secrets
  resources :application_environments
  resources :environments
  resources :applications
  devise_for :users
  root to: "home#index"
end

app/models/application_environment.rb
class ApplicationEnvironment < ApplicationRecord
  belongs_to :application
  belongs_to :environment
  has_one :postgresql
  has_one :redis, class_name: "Redi"
  has_one :elastic_search
  has_many :secrets

  def chroot
    "#{application.name}/#{environment.name}"
  end
end

app/controllers/application_environments_controller.rb
class ApplicationEnvironmentsController < LoggedInController # < ApplicationController
  before_action :load_application_environment, only: [:show, :edit, :update, :destroy]
  respond_to :html

  def index
    @application_environments = ApplicationEnvironment.all
  end

  def show
    respond_with @application_environment
  end

  def new
    @application_environment = ApplicationEnvironment.new
  end

  def edit
    respond_with @application_environment
  end

  def create
    @application_environment = ApplicationEnvironment.new(application_environment_params)
    flash[:notice] = "Application environment was successfully created." if @application_environment.save
    respond_with @application_environment
  end

  def update
    if @application_environment.update(application_environment_params)
      flash[:notice] = "Application environment was successfully updated."
    end
    respond_with @application_environment
  end

  def destroy
    @application_environment.destroy
    flash[:notice] = "Application environment was successfully destroyed."
    respond_with @application_environment
  end

  private

  def load_application_environment
    @application_environment = ApplicationEnvironment.find(params[:id])
  end

  def application_environment_params
    params.require(:application_environment).permit(:application_id, :environment_id, :rails_env)
  end
end

app/helpers/application_environments_helper.rb
module ApplicationEnvironmentsHelper
end

app/views/application_environments/_form.html.haml
= simple_form_for @application_environment, html: { class: "form-horizontal" },
                                               wrapper: :horizontal_form do |f|
  = f.error_notification

  .form-inputs
    = f.select :application_id, Application.all.collect { |a| [a.name, a.id] }
    = f.select :environment_id, Environment.all.collect { |e| [e.name, e.id] }
    = f.input :rails_env

  .form-actions
    = f.button :submit, class: "btn btn-primary"

app/views/application_environments/edit.html.haml
- title "Editing application_environment"

= render "form"

%br
= link_to "Show", @application_environment, class: 'btn btn-sm btn-success'
\|
= link_to "Back", application_environments_path

app/views/application_environments/index.html.haml
- title "Mappings of Applications to Environments"

%table.table.table-condensed
  %thead
    %tr
      %th Application
      %th Environment
      %th Rails Environment
      %th

  %tbody
    - @application_environments.each do |application_environment|
      %tr
        %td= application_environment.application.name
        %td= application_environment.environment.name
        %td= application_environment.rails_env.capitalize
        %td
          = link_to "Show", application_environment, class: "btn btn-xs btn-success"
          = link_to "Edit", edit_application_environment_path(application_environment), class: "btn btn-xs btn-info"
          = link_to "Destroy", application_environment, :method => :delete,
                               :data => { :confirm => "Are you sure?" },
                               class: "btn btn-xs btn-danger"

%br

= link_to "New Application Environment", new_application_environment_path, class: "btn btn-primary"

app/views/application_environments/new.html.haml
- title "New application_environment"

= render "form"

%br
= link_to "Back", application_environments_path

app/views/application_environments/show.html.haml
- title "application_environment #{@application_environment.id}"
%p
  %b Application:
  = @application_environment.application_id
%p
  %b Environment:
  = @application_environment.environment_id
%p
  %b Rails env:
  = @application_environment.rails_env

%br
= link_to "Edit", edit_application_environment_path(@application_environment), class: 'btn btn-sm btn-primary'
\|
= link_to "Back", application_environments_path