config/routes.rb
Rails.application.routes.draw do
  resources :elastic_searches
  resources :redis
  resources :postgresqls
  resources :secrets
  resources :application_environments
  resources :environments
  resources :applications
  devise_for :users
  root to: "home#index"
end

app/models/secret.rb
class Secret < ApplicationRecord
  belongs_to :application_environment
  has_one :application, through: :application_environment
  has_one :environment, through: :application_environment

  validates :key, presence: true
  validates :value, presence: true

  after_save :update_consul

  def update_consul
    Diplomat::Kv.put(application_environment.chroot+'/secrets/'+key, value, dc: environment.consul_dc)
  end
end

app/controllers/secrets_controller.rb
class SecretsController < LoggedInController # < ApplicationController
  before_action :load_secret, only: [:show, :edit, :update, :destroy]
  respond_to :html

  def index
    @secrets = Secret.all
  end

  def show
    respond_with @secret
  end

  def new
    @secret = Secret.new
  end

  def edit
    respond_with @secret
  end

  def create
    @secret = Secret.new(secret_params)
    flash[:notice] = "Secret was successfully created." if @secret.save
    respond_with @secret
  end

  def update
    if @secret.update(secret_params)
      flash[:notice] = "Secret was successfully updated."
    end
    respond_with @secret
  end

  def destroy
    @secret.destroy
    flash[:notice] = "Secret was successfully destroyed."
    respond_with @secret
  end

  private

  def load_secret
    @secret = Secret.find(params[:id])
  end

  def secret_params
    params.require(:secret).permit(:application_environment_id, :key, :value)
  end
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/views/secrets/_form.html.haml
= simple_form_for @secret, html: { class: "form-horizontal" },
                                               wrapper: :horizontal_form do |f|
  = f.error_notification

  .form-inputs
    = f.select :application_environment_id, ApplicationEnvironment.all.collect { |ae| [ae.application.name+' '+ae.rails_env, ae.id] }
    = f.input :key
    = f.input :value

  .form-actions
    = f.button :submit, class: "btn btn-primary"

app/views/secrets/edit.html.haml
- title "Editing secret"

= render "form"

%br
= link_to "Show", @secret, class: 'btn btn-sm btn-success'
\|
= link_to "Back", secrets_path

app/views/secrets/index.html.haml
- title "Secrets"

%table.table.table-condensed
  %thead
    %tr
      %th Application
      %th Environment
      %th Key
      %th Value
      %th

  %tbody
    - @secrets.each do |secret|
      %tr
        %td= secret.application.name
        %td= secret.environment.name
        %td= secret.key
        %td= secret.value
        %td
          = link_to "Show", secret, class: "btn btn-xs btn-success"
          = link_to "Edit", edit_secret_path(secret), class: "btn btn-xs btn-info"
          = link_to "Destroy", secret, :method => :delete,
                               :data => { :confirm => "Are you sure?" },
                               class: "btn btn-xs btn-danger"

%br

= link_to "New Secret", new_secret_path, class: "btn btn-primary"

app/views/secrets/new.html.haml
- title "New secret"

= render "form"

%br
= link_to "Back", secrets_path

app/views/secrets/show.html.haml
- title "secret #{@secret.id}"
%p
  %b Application environment:
  = @secret.application_environment_id
%p
  %b Key:
  = @secret.key
%p
  %b Value:
  = @secret.value

%br
= link_to "Edit", edit_secret_path(@secret), class: 'btn btn-sm btn-primary'
\|
= link_to "Back", secrets_path