config/routes.rb
Rails.application.routes.draw do
  resources :elastic_searches
  resources :redis
  resources :postgresqls
  resources :secrets
  resources :application_environments
  resources :environments
  resources :applications
  devise_for :users
  root to: "home#index"
end

app/models/environment.rb
class Environment < ApplicationRecord
  has_many :application_environments, dependent: :destroy
  has_many :applications, through: :application_environments
  has_many :secrets, through: :application_environments
  has_many :postgresqls, through: :application_environments
  has_many :redis, through: :application_environments
  has_many :elastic_searches, through: :application_environments

  validates :name, presence: true
end

app/controllers/environments_controller.rb
class EnvironmentsController < LoggedInController # < ApplicationController
  before_action :load_environment, only: [:show, :edit, :update, :destroy]
  respond_to :html

  def index
    @environments = Environment.all
  end

  def show
    respond_with @environment
  end

  def new
    @environment = Environment.new
  end

  def edit
    respond_with @environment
  end

  def create
    @environment = Environment.new(environment_params)
    flash[:notice] = "Environment was successfully created." if @environment.save
    respond_with @environment
  end

  def update
    if @environment.update(environment_params)
      flash[:notice] = "Environment was successfully updated."
    end
    respond_with @environment
  end

  def destroy
    @environment.destroy
    flash[:notice] = "Environment was successfully destroyed."
    respond_with @environment
  end

  private

  def load_environment
    @environment = Environment.find(params[:id])
  end

  def environment_params
    params.require(:environment).permit(:name, :consul_dc)
  end
end

app/helpers/environments_helper.rb
module EnvironmentsHelper
end

app/views/environments/_form.html.haml
= simple_form_for @environment, html: { class: "form-horizontal" },
                                               wrapper: :horizontal_form do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :consul_dc

  .form-actions
    = f.button :submit, class: "btn btn-primary"

app/views/environments/edit.html.haml
- title "Editing environment"

= render "form"

%br
= link_to "Show", @environment, class: 'btn btn-sm btn-success'
\|
= link_to "Back", environments_path

app/views/environments/index.html.haml
- title "Environments"

%table.table.table-condensed
  %thead
    %tr
      %th Name
      %th Consul Datacenter Name
      %th

  %tbody
    - @environments.each do |environment|
      %tr
        %td= environment.name
        %td= environment.consul_dc
        %td
          = link_to "Show", environment, class: "btn btn-xs btn-success"
          = link_to "Edit", edit_environment_path(environment), class: "btn btn-xs btn-info"
          = link_to "Destroy", environment, :method => :delete,
                               :data => { :confirm => "Are you sure?" },
                               class: "btn btn-xs btn-danger"

%br

= link_to "New Environment", new_environment_path, class: "btn btn-primary"

app/views/environments/new.html.haml
- title "New environment"

= render "form"

%br
= link_to "Back", environments_path

app/views/environments/show.html.haml
- title "environment #{@environment.id}"
%p
  %b Name:
  = @environment.name
%p
  %b Consul dc:
  = @environment.consul_dc

%br
= link_to "Edit", edit_environment_path(@environment), class: 'btn btn-sm btn-primary'
\|
= link_to "Back", environments_path